// channels.js
const channels = [
  { id: "mtvclassic", name: "🔘MTV CLASSIC", src: "https://fl3.moveonjoy.com/MTV_CLASSIC/index.m3u8", type: "hls" },
  { id: "mtvlive", name: "🔘MTV LIVE", src: "https://fl5.moveonjoy.com/MTV_LIVE/index.m3u8", type: "hls" },
  { id: "syfy", name: "🔘SYFY", src: "https://fl3.moveonjoy.com/SYFY/index.m3u8", type: "hls" },
  { id: "shwtm", name: "🔘SHOW TIME", src: "https://fl3.moveonjoy.com/SHOWTIME/index.m3u8", type: "hls" },
  { id: "shwtm2", name: "🔘SHOW TIME 2", src: "https://fl3.moveonjoy.com/SHOWTIME_2/index.m3u8", type: "hls" },
  { id: "shwtmnx", name: "🔘SHOW TIME NX", src: "https://fl3.moveonjoy.com/SHOWTIME_NEXT/index.m3u8", type: "hls" },
  { id: "naturescape", name: "🔘NATURESCAPE", src: "https://lotus.stingray.com/manifest/naturescape-a003-montreal/samsungtvplus/f7ed86a4-b8ac-38e0-a745-710077a95be6/3291200/manifest.m3u8", type: "hls" },
  { id: "lovenature", name: "🔘LOVE NATURE", src: "https://aegis-cloudfront-1.tubi.video/dc8bda97-ce9e-4091-b4e8-11254dea4da6/1080p-cc/index.m3u8", type: "hls" },
  { id: "90s", name: "🔘90s", src: "https://lotus.stingray.com/manifest/ose-142ads-montreal/samsungtvplus/f5102ca4-edd7-30ac-a357-877f60db023b/1790800/manifest.m3u8", type: "hls" },
  { id: "rtlgold", name: "🔘RTL GOLD", src: "https://stream.rtl.lu/data/live/tele/rtlgold/1080p.m3u8", type: "hls" },
  { id: "omrop", name: "🔘Omrop NL", src: "https://d3pvma9xb2775h.cloudfront.net/live/omropfryslan/f8f68bd5/playlist.m3u8", type: "hls" },
  { id: "fox13", name: "🔘FOX 13", src: "https://apollo.production-public.tubi.io/live/ac-kcpq.m3u8", type: "hls" },
  { id: "tv5", name: "🔘TV5 FINLAND", src: "https://live-fi.tvkaista.net/tv5/live.m3u8", type: "hls" },
  { id: "trtspor", name: "🔘TRT SPOR", src: "https://tv-trtspor1.medya.trt.com.tr/master.m3u8", type: "hls" },
  { id: "trtyildiz", name: "🔘TRT YLDZ SPOR", src: "https://tv-trtspor2.medya.trt.com.tr/master.m3u8", type: "hls" },
  { id: "nhk", name: "🔘NHK WORLD", src: "https://master.nhkworld.jp/nhkworld-tv/playlist/live.m3u8", type: "hls" },
  { id: "m2", name: "🔘M2 UKR", src: "https://live.m2.tv/hls3/720/stream.m3u8", type: "hls" },
  { id: "dsny", name: "🔘DISNEY XD", src: "https://fl3.moveonjoy.com/DISNEY_XD/index.m3u8", type: "hls" },
  { id: "trtbelgesel", name: "🔘TRT BELGESEL", src: "https://tv-trtbelgesel.medya.trt.com.tr/master.m3u8", type: "hls" },
  { id: "tlc", name: "🔘TLC", src: "https://dogus-live.daioncdn.net/tlc/tlc_720p.m3u8", type: "hls" },
  { id: "natgeo", name: "🔘NAT-GEO", src: "https://fl3.moveonjoy.com/National_Geographic/index.m3u8", type: "hls" },
  { id: "dmax", name: "🔘D-MAX", src: "https://dogus-live.daioncdn.net/dmax/dmax_720p.m3u8", type: "hls" },
  { id: "france24", name: "🔘FRANCE 24", src: "https://live.france24.com/hls/live/2037218-b/F24_EN_HI_HLS/master_5000.m3u8", type: "hls" },
  { id: "aljazeera", name: "🔘AL JAZEERA", src: "https://live-hls-web-aje.getaj.net/AJE/index.m3u8", type: "hls" },
  { id: "trt1", name: "🔘TRT1", src: "https://tv-trt1.medya.trt.com.tr/master.m3u8", type: "hls" },
  { id: "trt2", name: "🔘TRT 2", src: "https://tv-trt2.medya.trt.com.tr/master_720.m3u8", type: "hls" },
  { id: "bein1", name: "🔘NOW", src: "https://uycyyuuzyh.turknet.ercdn.net/nphindgytw/nowtv/nowtv.m3u8", type: "hls" },
  { id: "halktv", name: "🔘HALK TV", src: "https://halktv-live.daioncdn.net/halktv/halktv.m3u8", type: "hls" },
  { id: "tele1", name: "🔘TELE 1", src: "fNqmmqNNGp8", type: "youtube" },
  { id: "sozcu", name: "🔘SÖZCÜ TV", src: "ztmY_cCtUl0", type: "youtube" },
  { id: "beinbox1", name: "🔘BEIN1", src: "https://tv.arectv34.sbs/live/box1.m3u8", type: "hls" },
  { id: "beinact", name: "🔘BEIN ACTION", src: "https://tv.arectv34.sbs/live/bsaction1.m3u8", type: "hls" },
  { id: "beinbox2", name: "🔘BEIN BOX2", src: "https://tv.arectv34.sbs/live/box2.m3u8", type: "hls" },
  { id: "beinbox3", name: "🔘BEIN BOX3", src: "https://tv.arectv34.sbs/live/box3.m3u8", type: "hls" },
  { id: "beinfam", name: "🔘BEIN FAMILY", src: "https://tv.arectv34.sbs/live/bsfamily.m3u8", type: "hls" },
  { id: "beinprem", name: "🔘BEIN PREMIERE", src: "https://tv.arectv34.sbs/live/bspremier1.m3u8", type: "hls" },
  { id: "beinstars", name: "🔘BEIN STARS", src: "https://tv.arectv34.sbs/live/bsstars.m3u8", type: "hls" },
  { id: "fxtr", name: "🔘FX TR", src: "https://saran-live.ercdn.net/fx/index.m3u8", type: "hls" },
  { id: "bbcearth", name: "🔘BBC EARTH", src: "https://tv.arectv34.sbs/live/bbc.m3u8", type: "hls" },
  { id: "discoverytr", name: "🔘DISCOVERY TR", src: "https://tv.arectv34.sbs/live/discovery.m3u8", type: "hls" },
  { id: "natgeotr", name: "🔘NATGEO TR", src: "https://saran-live.ercdn.net/natgeohd/index.m3u8", type: "hls" },
  { id: "natgeowildtr", name: "🔘NATGEO WILD TR", src: "https://saran-live.ercdn.net/natgeowild/index.m3u8", type: "hls" },
  { id: "tarihtv", name: "🔘TARİH TV", src: "https://tv.arectv34.sbs/live/tarihtv.m3u8", type: "hls" },
  { id: "tlctr", name: "🔘TLC TR", src: "https://dogus-live.daioncdn.net/tlc/tlc.m3u8", type: "hls" },
  { id: "viasathis", name: "🔘VIASAT HISTORY", src: "https://tv.arectv34.sbs/live/viasathistory.m3u8", type: "hls" },
  { id: "viasatex", name: "🔘VIASAT EXPLR", src: "https://tv.arectv34.sbs/live/viasatexplore.m3u8", type: "hls" },
  { id: "cartoon", name: "🔘CARTOON NTWRK", src: "https://tv.arectv34.sbs/live/cartoonnetwork.m3u8", type: "hls" },
  { id: "nick", name: "🔘NICKELODEON", src: "http://fl1.moveonjoy.com/NICKELODEON/index.m3u8", type: "hls" },
  { id: "euro1", name: "🔘EUROSPORT 1", src: "https://tv.arectv34.sbs/live/euro1.m3u8", type: "hls" },
  { id: "euro2", name: "🔘EUROSPORT 2", src: "https://tv.arectv34.sbs/live/euro2.m3u8", type: "hls" },
  { id: "komedi", name: "🔘SİNEMA KOMEDİ", src: "https://tv.arectv34.sbs/live/sinemakomedi.m3u8", type: "hls" },
  { id: "aksiyon", name: "🔘SİNEMA AKSİYON", src: "https://tv.arectv34.sbs/live/sinemaaksiyon2.m3u8", type: "hls" },
  { id: "tabi1", name: "🔘TABİ 1", src: "https://tv.arectv34.sbs/live/tabi1.m3u8", type: "hls" },
  { id: "tabi2", name: "🔘TABİ 2", src: "https://tv.arectv34.sbs/live/tabi2.m3u8", type: "hls" },
  { id: "tabi3", name: "🔘TABİ 3", src: "https://tv.arectv34.sbs/live/tabi3.m3u8", type: "hls" },
  { id: "tabi4", name: "🔘TABİ 4", src: "https://tv.arectv34.sbs/live/tabi4.m3u8", type: "hls" },
  { id: "tabi5", name: "🔘TABİ 5", src: "https://tv.arectv34.sbs/live/tabi5.m3u8", type: "hls" },
  { id: "tabi6", name: "🔘TABİ 6", src: "https://tv.arectv34.sbs/live/tabi6.m3u8", type: "hls" },
  { id: "ssport1", name: "🔘S SPORT", src: "https://lively1.cf4-85e.workers.dev/static/ss11.m3u8", type: "hls" },
  { id: "ssport2", name: "🔘S SPORT 2", src: "https://lively1.cf4-85e.workers.dev/static/ss2.m3u8", type: "hls" },
  { id: "ssport3", name: "🔘S SPORT 3", src: "https://tv.arectv34.sbs/live/pl3.m3u8", type: "hls" },
  { id: "smart1", name: "🔘SPOR SMART 1", src: "https://tv.arectv34.sbs/live/smart1.m3u8", type: "hls" },
  { id: "smart2", name: "🔘SPOR SMART 2", src: "https://tv.arectv34.sbs/live/smart2.m3u8", type: "hls" },
  { id: "tivibu1", name: "🔘TİVİBU SPOR 1", src: "https://tv.arectv34.sbs/live/t1.m3u8", type: "hls" },
  { id: "tivibu2", name: "🔘TİVİBU SPOR 2", src: "https://tv.arectv34.sbs/live/t2.m3u8", type: "hls" },
  { id: "tivibu3", name: "🔘TİVİBU SPOR 3", src: "https://tv.arectv34.sbs/live/t3.m3u8", type: "hls" },
  { id: "tivibu4", name: "🔘TİVİBU SPOR 4", src: "https://tv.arectv34.sbs/live/t4.m3u8", type: "hls" }
];
